### ISSUE TITLE
Bolt doesn't error if given an unreachable host

### ISSUE THREAD

**Issue by ashwinvin** [hiro-codes/bolt#62]
# Problem

Bolt currently silently fails if its made to request an unreachable host. It also appears that bolt doesn't check if the given URL has a valid form.

# Solution

Bolt should throw an error when its met these conditions. 
_**Suggested error format:**_

1. ```Host unreachable: {url} cannot be reached```
2. ```Invalid URL: {url} is malformed```

**Comment by 0xhiro** [comment]
This issue has been fixed in the master branch. It will be included with the next release.
