### ISSUE TITLE
makefile in a Rust project, really?

### ISSUE THREAD

**Issue by anas-elgarhy** [hiro-codes/bolt#66]
I understand the point here, but we have [just](https://github.com/casey/just), the replacement to `make` that written in our language
It is true that it doesn't have all the `make` features, but I don't see you using any of them

So I think it's a good idea if we replace the `makefile` with `justfile`, and I'll be happy if I do this

**Comment by 0xhiro** [comment]
Could you make a pull request replacing the makefile with a `justfile`?

**Comment by anas-elgarhy** [comment]
Yes, I can.
I don't see the point of keeping the `makefile`

**Comment by 0xhiro** [comment]
Because make is installed on most computers, and people may prefer it due to being familiar with it.
