### ISSUE TITLE
[Issue] Problems when building the proyect

### ISSUE THREAD

**Issue by RafaelMoralesV** [hiro-codes/bolt#71]
I'm having issues when building the project; not sure what this is about, tbh. I'm not too savy in yew :^(

![image](https://user-images.githubusercontent.com/42483328/231621203-5fe10616-b7a1-487e-966a-d31d77cd2845.png)

I tried a clean build, and both make and just, but haven't really figured it out.

There might be hidden steps I'm not seeing in the readme?

![image](https://user-images.githubusercontent.com/42483328/231621531-8ddc2f58-73f6-47a5-a93b-5cd47288339c.png)

This is my neofetch, if it helps in any way

Thanks for building this btw! I was looking for some alternative to postman for a while.

**Comment by 0xhiro** [comment]
Based on the error message, it looks like this is a network error.

**Comment by 0xhiro** [comment]
Which command are you running?

**Comment by RafaelMoralesV** [comment]
> Which command are you running?

The `just build` command. I tried `make build` too, but had the same error.
I ran the `make setup` command at first too, using make instead of just, tho I don't expect any difference

This is the output I get now:

![image](https://user-images.githubusercontent.com/42483328/231633634-2ac347e4-84a6-44d8-8bff-356284c0c1fd.png)

**Comment by 0xhiro** [comment]
Yeah, `make` and `just` run the exact same commands

**Comment by 0xhiro** [comment]
This is a DNS resolution error, as much as i can see from the screenshot

**Comment by 0xhiro** [comment]
The command causing the error is the `trunk build` command

**Comment by 0xhiro** [comment]
I'm looking this up at the trunk repository to see if there have been similar errors reported

**Comment by RafaelMoralesV** [comment]
https://users.rust-lang.org/t/trunk-not-downloading-wasm-bindgen/88316

I found this link and this answer for pretty much the same error

![image](https://user-images.githubusercontent.com/42483328/231634342-6f583acc-eed8-488b-a424-5f4658261973.png)

**Comment by 0xhiro** [comment]
Okay so are you running a server on your computer?

**Comment by RafaelMoralesV** [comment]
I'm checking what is running right now; I might have left something running

**Comment by 0xhiro** [comment]
Check out this issue here: https://github.com/thedodd/trunk/issues/453

**Comment by RafaelMoralesV** [comment]
Nothing strange was running, so the error I found was probably a miss

I did find this, though!

https://github.com/prisma/prisma/issues/13370

This is the contents of pop_os' `/etc/resolve.conf` file, same content as the issue.

![image](https://user-images.githubusercontent.com/42483328/231635783-d69b62c0-56a9-4f7f-9bb2-78dbba01596a.png)

I commented out the `search --` line and got to build the proyect, tho it did fail at some missing packages (libsoup-2.4 is missing in my system it seems?)

![image](https://user-images.githubusercontent.com/42483328/231636284-e58ce8cc-6ca8-44d9-81ce-50aebb4c8b15.png)

Gonna search about it and see if I can complete a build

**Comment by 0xhiro** [comment]
Yeah you might encounter many missing dependencies

**Comment by 0xhiro** [comment]
Installing `libsoup` should fix it

**Comment by RafaelMoralesV** [comment]
Seems like everything is done now

As a TL;DR for anyone with this issue, look on your `/etc/resolve.conf` file which might be causing issues, and install `libsoup2.4-dev` and `libwebkit2gtk-4.0-dev` as dependencies

Thanks for your time Hiro!

**Comment by 0xhiro** [comment]
Thanks!
