### ISSUE TITLE
Persist requests

### ISSUE THREAD

**Issue by OAyomide** [hiro-codes/bolt#80]
Creating a request, opening and closing it, it resets to empty and all requests are deleted.

**Comment by 0xhiro** [comment]
Can you describe further what you mean? Could you also include a screen recording?

**Comment by OAyomide** [comment]
https://user-images.githubusercontent.com/26779597/232532966-6b5aacaf-01a6-4fed-b811-1f284b8a88e4.mov

**Comment by 0xhiro** [comment]
Oh! right! This will be worked on and included in a future version.

**Comment by 0xhiro** [comment]
This feature has been implemented in the latest version. Please update! Thanks.
